version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
      - UPTIME_ROBOT_API_KEY=${UPTIME_ROBOT_API_KEY}
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'


